### ISSUE TITLE
Unable to edit .stignore file via web GUI

### ISSUE THREAD

**Issue by tguser** [syncthing/syncthing-android#640]
Version: 0.7.17, ST v0.12.22, Linux (ARM)

I tried to edit .stignore file via web GUI (from my PC) but it fails with error:

`2016-05-10 16:10:50: Saving .stignore: chmod /storage/emulated/0/.syncthing.tmp.798561500: operation not permitted`

I can only click on OK button for this message and I have to restart ST service (because it say to do it to activate the new configuration).
After the restart .stignore is the same as before the editing.

**Comment by capi** [comment]
Which Android version are you running? Sounds to me like you might have run as `root` once?

**Comment by tguser** [comment]
I'm running latest stock Android 6.0.1 (april patch) on a N5X 

I've never rooted it so I have never enabled run as root.
My config syncs all user's folders excluding "/Android".

I am sure when I installed syncthing (3 or 4 app updates ago AND on Android 6.0.1) I was able to edit stignore (it is when I excluded "/Android" folder).

**Comment by AudriusButkevicius** [comment]
I suspect you are simply syncing a location where the app does not have permission to write, in general. Nothing related to versions.

**Comment by tguser** [comment]
/storage/emulated/0/  is my user folder. There are the default folders like "Music", "Notifications" and "Telegram"...
It is my home directory where the syncthing app created files like .stignore and .stfolder. It is strange that now it cannot edit .stignore file.

**Comment by Zillode** [comment]
I think `chmod` should not be used on the Android platform?

**Comment by AudriusButkevicius** [comment]
We use it very often, so I'd be surprised if it's that.

**Comment by Zillode** [comment]
https://github.com/syncthing/syncthing/issues/2472

**Comment by AudriusButkevicius** [comment]
And that fix is still there.
GOOS has changed when we moved away from cgo?

**Comment by Nutomic** [comment]
We're building with `GOOS=linux`. According to @Zillode there was some problem with `GOOS=android`, but I don't remember what that was.

**Comment by Zillode** [comment]
That's right, I forgot about that. Compiling with GOOS=android still doesn't work with Go1.6:
```
warning: unable to find runtime/cgo.a
/Users/lhoste/tmp/syncthing-android/ext/golang/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/fm/mpfdm95d6l541n2wk54ylh5w0000gn/T/go-link-308662440/go.o, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x01 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/fm/mpfdm95d6l541n2wk54ylh5w0000gn/T/go-link-308662440/go.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
(Note that we deliberately set export [CGO_ENABLED=0](https://github.com/syncthing/syncthing-android/blob/1fba3dd53e91b96d113ec3706824817f726f5f21/make-go.bash#L9))

**Comment by Nutomic** [comment]
Did you file an issue at golang?

**Comment by Nutomic** [comment]
Should be fixed in the next release.
