### PR TITLE
Fix crash in settings onApiChange call (fixes #1084)

### LINKED ISSUE #1084: Pre-launch check failures
```
05-09 19:42:08.759: E/AndroidRuntime(17255): FATAL EXCEPTION: Thread-1131
05-09 19:42:08.759: E/AndroidRuntime(17255): Process: com.nutomic.syncthingandroid, PID: 17255
05-09 19:42:08.759: E/AndroidRuntime(17255): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6530)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:900)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.view.View.requestLayout(View.java:17290)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AbsListView.requestLayout(AbsListView.java:1985)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:821)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6189)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:271)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.Preference.notifyChanged(Preference.java:1136)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at android.preference.Preference.setEnabled(Preference.java:759)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.activities.SettingsActivity$SettingsFragment.onApiChange(SettingsActivity.java:265)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.onApiChange(SyncthingService.java:367)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.access$000(SyncthingService.java:34)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.<init>(SyncthingService.java:196)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService.lambda$onStartCommand$0$SyncthingService(SyncthingService.java:126)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingService$$Lambda$0.onKilled(Unknown Source)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable.lambda$killSyncthing$0$SyncthingRunnable(SyncthingRunnable.java:292)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable$$Lambda$0.run(Unknown Source)
05-09 19:42:08.759: E/AndroidRuntime(17255): 	at java.lang.Thread.run(Thread.java:831)
```

### PR DESCRIPTION
**Pull request by Nutomic**
Coded this in the web editor so not sure if this compiles.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Nice try ;)

**Comment by Nutomic** [comment]
Oops, looks like I used Kotlin syntax instead of Java. Can't remember the syntax without IDE, and I don't want to install it now :D

@calmh Can you please take me off the Travis CI notifications for broken builds? Don't need to know about every failure in the repo.

**Comment by calmh** [comment]
I have no influence over any Travis setup, sorry.

**Comment by Catfriend1** [comment]
]/opt/buildagent/work/19a8ed19ae4d1032/app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java:361: error: '(' or '[' expected
[21:54:33]        mHandler.post(new Runnable {
[21:54:33]                                   ^
[21:54:33]/opt/buildagent/work/19a8ed19ae4d1032/app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingService.java:361: error: ';' expected
[21:54:33]        mHandler.post(new Runnable {
[21:54:33]                                    ^

**Comment by Catfriend1** [comment]
It does not build, you should probably remove the final.

**Comment by Nutomic** [comment]
Damn, it's really no fun programming like this.

**Comment by Nutomic** [comment]
Okay finally. This should definitely work, but it won't hurt if you give it a try first @Catfriend1

**Comment by Catfriend1** [comment]
@Nutomic hmm I noticed two Syncthing processes running simultaneously, even after total uninstall and reinstall of the debug apk. Also, the localhost appears as the device name instead of my build.model.
screenshot_20180510-173044
screenshot_20180510-173055

**Comment by Catfriend1** [comment]
Okay my fault, had the release accidentially running in parallel. Wonder why the localhost device came up in the debug instance... So, I can confirm the apk working on Android 7.1.2. Problem is, I dont have the Android 5 phone gplay console displayed the error for. This feels like nothing changed to me since 0.10.10

**Comment by Nutomic** [comment]
The error has nothing to do with the Android version, it just happens because Syncthing is restarted, and a callback in the settings activity is trying to modify the layout from a background thread. Now this is all happening in the foreground like it should, so the error won't happen any more.

**Comment by Catfriend1** [comment]
@Nutomic Before this PR I had the problem that hitting the restart button on syncthing's Web UI always got me stuck with an exited syncthing core process (according to the log) and the app UI showing an outdated state which may make a user thinkting it is still running up fine. (folder up2date and green, no loading indicator).
I built after this PR and now hitting the restart button on the Web UI works correctly.
