### ISSUE TITLE
Build does not work with go 1.10

### ISSUE THREAD

**Issue by jaoh** [syncthing/syncthing-android#1047]
I tried building the commit 
https://github.com/syncthing/syncthing-android/commit/7194e25a5cacff14b3df85f4cf2e17d415a20038
With go 1.10. The build native target of Gradle fails wit compilation problems

./gradlew --scan buildNative assembleDebug

Configure project :app Signing not ready. Did you specify a signingConfig for the variation Release?

Task syncthing:buildNative FAILED Starting build for arm

Building Syncthing

`# runtime/cgo

In file included from gcc_libinit.c:8:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/pthread.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/time.h:33: In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/time.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/select.h:36:
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:96:18: error: expected ‘;’ at end of declaration list
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:85:22: note: expanded from macro ‘sa_handler’
In file included from gcc_libinit.c:8:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/pthread.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/time.h:33:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/time.h:37:
In file included from /home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/sys/select.h:36:
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:12: error: expected ‘)’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:86:24: note: expanded from macro ‘sa_sigaction’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:10: note: to match this ‘(’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:97:12: error: duplicate member ‘_u’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/asm/signal.h:86:22: note: expanded from macro ‘sa_sigaction’
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin/…/sysroot/usr/include/signal.h:96:18: note: previous declaration is here
/home/jaoh/git/syncthing-android/syncthing/gobuild/standalone-ndk/android-14-arm/bin /…/sysroot/usr/include/asm/signal.h:85:20: note: expanded from macro ‘sa_handler’ `  

This should be noted in the README.md so that others do not experience this problem.

**Comment by jaoh** [comment]
There are some changes in go1.10 regarding the handling of pointers 

https://golang.org/doc/go1.10

> Cgo now translates some C types that would normally map to a pointer type in Go, to a uintptr instead. These types include the CFTypeRef hierarchy in Darwin's CoreFoundation framework and the jobject hierarchy in Java's JNI interface.
> These types must be uintptr on the Go side because they would otherwise confuse the Go garbage collector; they are sometimes not really pointers but data structures encoded in a pointer-sized integer. Pointers to Go memory must not be stored in these uintptr values.
> Because of this change, values of the affected types need to be zero-initialized with the constant 0 instead of the constant nil. Go 1.10 provides gofix modules to help with that rewrite:

If this is a problem in the context of JNI this could also be a possible problem with the Android NDK.

**Comment by Catfriend1** [comment]
| This should be noted in the README.md so that others do not experience this problem. |
Refer to: 
https://github.com/syncthing/syncthing-android/blob/master/README.md#dependencies
which then links the syncthing core docs where Go 1.9 is stated as the version to build with.
We can't do anything about the build problem in this repo because it has to be fixed upstream.

**Comment by AudriusButkevicius** [comment]
No, syncthing is built with 1.10.

**Comment by imsodin** [comment]
Actually I don't think so - it's probably up-upstream, i.e. a cgo problem. I believe this is specific to one gcc versions used in the wrapper trough the NDK (SDK?) to build syncthing. I was too lazy to narrow it down myself yet (was hoping 1.10.1 would fix it, as it had some cgo fixes in it). So what is needed to do is narrow it down and report to GO if it turns out to be true.

**Comment by Catfriend1** [comment]
Still not building with go 1.10.3

**Comment by imsodin** [comment]
I posted (a bit hastily) in the Golang forum: https://forum.golangbridge.org/t/failure-to-build-with-android-ndk-since-go1-10/10194
Maybe something comes out of it.

**Comment by calmh** [comment]
And caused me significant cognitive dissonance when there was your avatar and a Syncthing topic at the top of the the non-Syncthing forum I switched to from the Syncthing forum. Headache is only now dissipating.

**Comment by bt90** [comment]
Is the android build error related to this one? https://github.com/android-ndk/ndk/issues/681

**Comment by bt90** [comment]
Further observations in [build-syncthing.py](https://github.com/syncthing/syncthing-android/blob/988bbb089373856821129e4b3a625925be8d5f08/syncthing/build-syncthing.py) invoking the go build:

* i couldn't find where the [GOARM](https://github.com/golang/go/wiki/GoArm) environment variable is set
* the `CXX` environment variable seems not to be set

Found this post, maybe it's helpful: https://github.com/golang/go/issues/20755#issuecomment-355016987

**Comment by capi** [comment]
I've long been using an older self-compiled version that simply works for my devices. Today I wanted to try out the latest master, and encountered this issue again. Is there any news on the issue? Is it safe to compile with go 1.9? In my case it's go 1.9.4.

**Comment by AudriusButkevicius** [comment]
Well "safe" essentially means there is no other option. I still have not looked into the issue.

**Comment by bt90** [comment]
Closed with #1265 ?
